FROM python:3.11

ENV PIP_TRUSTED_HOST="pypi.org files.pythonhosted.org"

WORKDIR /app

COPY . .

RUN pip install --no-cache-dir -r app/requirements.txt

EXPOSE 8000

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
